import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | RETINA Wealth',
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-24 md:py-32">
      <h1 className="text-3xl md:text-4xl font-bold text-slate-900 mb-2">Terms of Service</h1>
      <p className="text-sm text-slate-500 mb-12">Last updated: April 2026</p>

      <div className="prose prose-slate prose-sm max-w-none space-y-8">
        <section>
          <h2 className="text-xl font-bold text-slate-900 mb-3">1. Acceptance of Terms</h2>
          <p className="text-slate-600 leading-relaxed">By accessing or using the Retina Wealth platform (&quot;Service&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, you must not use the Service. We reserve the right to update these terms at any time, with changes effective upon posting.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 mb-3">2. Service Description</h2>
          <p className="text-slate-600 leading-relaxed">Retina Wealth provides automated, physics-based trading signal generation and order routing through connected third-party brokerage accounts. The Service analyses market data using proprietary models and executes trades on your behalf based on algorithmic signals. Retina Wealth is not a broker-dealer and does not hold, custody, or manage your funds directly.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 mb-3">3. Eligibility</h2>
          <p className="text-slate-600 leading-relaxed">You must be at least 18 years old and legally able to enter into binding agreements in your jurisdiction to use the Service. You are responsible for ensuring your use of the Service complies with all applicable laws and regulations in your country of residence.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 mb-3">4. Account & Brokerage Connection</h2>
          <p className="text-slate-600 leading-relaxed">To use the Service, you must create an account and connect a supported third-party brokerage account. You are solely responsible for maintaining the security of your account credentials. Retina Wealth accesses your brokerage account only to execute trades generated by the engine and does not withdraw, transfer, or otherwise move your funds.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 mb-3">5. Fees & Billing</h2>
          <p className="text-slate-600 leading-relaxed">Accounts with portfolio values under $10,000 may use the Service free of charge. Accounts exceeding this threshold are subject to a monthly subscription fee as outlined on our pricing page. Fees are billed monthly and are non-refundable. We reserve the right to adjust pricing with 30 days&apos; written notice.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 mb-3">6. Risk Acknowledgement</h2>
          <p className="text-slate-600 leading-relaxed">Trading in financial markets involves substantial risk of loss. Past performance, including out-of-sample backtest results, does not guarantee future returns. You acknowledge that the use of algorithmic trading systems can result in the loss of some or all of your invested capital. You should not invest money you cannot afford to lose.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 mb-3">7. No Financial Advice</h2>
          <p className="text-slate-600 leading-relaxed">The Service does not constitute financial advice, investment advice, or any other form of professional advice. Retina Wealth does not recommend any specific securities, transactions, or investment strategies. All trading decisions are executed algorithmically based on quantitative models, not personalised recommendations.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 mb-3">8. Limitation of Liability</h2>
          <p className="text-slate-600 leading-relaxed">To the maximum extent permitted by law, Retina Wealth Ltd shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from your use of the Service.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 mb-3">9. Termination</h2>
          <p className="text-slate-600 leading-relaxed">You may cancel your account at any time. Upon cancellation, all automated trading will cease immediately. We may suspend or terminate your access to the Service at our discretion if we believe you have violated these terms or engaged in fraudulent or harmful activity.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 mb-3">10. Governing Law</h2>
          <p className="text-slate-600 leading-relaxed">These terms shall be governed by and construed in accordance with the laws of England and Wales. Any disputes arising from these terms or the Service shall be subject to the exclusive jurisdiction of the courts of England and Wales.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 mb-3">11. Contact</h2>
          <p className="text-slate-600 leading-relaxed">For questions about these terms, please contact us at <a href="mailto:legal@retinawealth.com" className="text-emerald-600 hover:underline">legal@retinawealth.com</a>.</p>
        </section>
      </div>
    </div>
  );
}
